name: Pull Request
on:
  pull_request:
    branches:
      - main

permissions:
  contents: read
  pull-requests: read
# Optional: allow write access to checks to allow the action to annotate code in the PR.
  checks: write

jobs:

  golint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.22

    - name: golangci-lint
      uses: golangci/golangci-lint-action@v6
      with:
        version: v1.59

  buflint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: bufbuild/buf-setup-action@v1
      - uses: bufbuild/buf-lint-action@v1

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.22

    - name: Build
      run: go build -a -v server/main.go

    - name: Test
      run: go test -v -cover ./...

